/**
 * WebMCPCodeGenerator - Generates WebMCP code from MCP tool definitions
 *
 * Output formats:
 * - Imperative JS (registerTool calls)
 * - Declarative HTML (form with tool attributes)
 * - TypeScript types
 */
import type { MCPToolDefinition } from '@wmcp/core';
import { generateImperativeCode, generateDeclarativeHTML } from '@wmcp/core';

export type OutputFormat = 'imperative-js' | 'declarative-html' | 'typescript' | 'all';

export interface GeneratorOptions {
  format: OutputFormat;
  proxyBaseUrl?: string;
  includePolyfill?: boolean;
  includeFeatureDetection?: boolean;
}

export class WebMCPCodeGenerator {
  private options: GeneratorOptions;

  constructor(options: GeneratorOptions) {
    this.options = options;
  }

  generate(tools: MCPToolDefinition[]): Map<string, string> {
    const files = new Map<string, string>();
    const { format } = this.options;

    if (format === 'imperative-js' || format === 'all') {
      files.set('webmcp-tools.js', this.generateImperativeJS(tools));
    }

    if (format === 'declarative-html' || format === 'all') {
      files.set('webmcp-forms.html', this.generateDeclarativeHTML(tools));
    }

    if (format === 'typescript' || format === 'all') {
      files.set('webmcp-types.d.ts', this.generateTypeScript(tools));
    }

    return files;
  }

  private generateImperativeJS(tools: MCPToolDefinition[]): string {
    const header = this.options.includePolyfill
      ? `// Polyfill for browsers without native WebMCP
import '@mcp-b/global';

`
      : '';

    const detection = this.options.includeFeatureDetection
      ? `// Feature detection
if (!('modelContext' in navigator)) {
    console.warn('WebMCP not supported. Include @mcp-b/global polyfill.');
}

`
      : '';

    const toolCode = tools
      .map((tool) => generateImperativeCode(tool, { proxyBaseUrl: this.options.proxyBaseUrl }))
      .join('\n\n');

    return `${header}${detection}// Generated by mcp2web - ${tools.length} tools
// Source: MCP Server tools/list
// Date: ${new Date().toISOString()}

${toolCode}
`;
  }

  private generateDeclarativeHTML(tools: MCPToolDefinition[]): string {
    const forms = tools
      .map((tool) => {
        const fields = Object.entries(tool.inputSchema.properties ?? {}).map(([name, prop]) => {
          const p = prop as unknown as Record<string, string>;
          return {
            name,
            type: p.type === 'number' ? 'number' : 'text',
            label: p.description ?? name,
            required: (tool.inputSchema.required ?? []).includes(name),
            placeholder: p.description,
          };
        });

        return generateDeclarativeHTML({
          action: `/api/${tool.name}`,
          method: 'POST',
          fields,
          hasToolAttributes: true,
          hasToolDescription: true,
          hasToolAutosubmit: true,
          suggestedToolName: tool.name,
        });
      })
      .join('\n\n');

    return `<!-- Generated by mcp2web - ${tools.length} tools -->
<!-- Date: ${new Date().toISOString()} -->

${forms}
`;
  }

  private generateTypeScript(tools: MCPToolDefinition[]): string {
    const interfaces = tools
      .map((tool) => {
        const props = Object.entries(tool.inputSchema.properties ?? {})
          .map(([name, prop]) => {
            const p = prop as unknown as Record<string, string>;
            const isRequired = (tool.inputSchema.required ?? []).includes(name);
            const tsType = p.type === 'number' ? 'number' : p.type === 'boolean' ? 'boolean' : 'string';
            return `  ${name}${isRequired ? '' : '?'}: ${tsType};`;
          })
          .join('\n');

        const interfaceName = pascalCase(tool.name) + 'Input';
        return `/** ${tool.description} */
export interface ${interfaceName} {
${props}
}`;
      })
      .join('\n\n');

    return `// Generated by mcp2web - ${tools.length} tool types
// Date: ${new Date().toISOString()}

${interfaces}
`;
  }
}

function pascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}
